language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@5.6.0

install:
  - npm install

script:
  - npm run lint
  - npm test -- --watch=false --code-coverage
